### ISSUE TITLE
Provide method to return the count of contained items in the CUDS containers

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-common#164]
A set of CUBA keywords will be added for the low level CUDS items.

```python
POINT
PARTICLE
BOND
EDGE
FACE
CELL
NODE
```

New method in CUDS containers

```python
  def count_of(self, item_type):
      """ Return the count of item_type in the container.

      Parameter
      ---------
      item_type : CUBA
          The CUBA enum of the type of the items to return the count of.         

      Returns
      -------
      count : int
          The number of items of item_type in the container.

      Raises
      ------
      ValueError :
          If the type of the item is not supported in the current container. 
      
      """
```

**tasks**:

- [ ] update the KEYWords yml and regenerate the CUBA enum
- [ ] update the uml diagrams
- [ ] Augment test template
- [ ] update the abstract classes
- [ ] update the concrete classes
- [ ] update the hdf5 back classes
